######################################################################
# Automatically generated by qmake (1.03a) Thu Aug 1 08:38:18 2002
######################################################################

TEMPLATE = app
CONFIG -= moc

# Input
LEXSOURCES += pas2dox.l
